services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - spyfall-net

  mongo:
    image: mongo:8.2.3
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - spyfall-net

networks:
  spyfall-net:
    driver: bridge

volumes:
  mongo-data:
